### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by tinmac** [bcandersen/tplink-st-edge#1]
Do we need an invite from the edge channel owner to install these drivers? 

- If so how do we find the owner & get an invite?

- If not how do we install these drivers

Sorry if its newb

**Comment by pavichokche** [comment]
Invitation link for TP-Link/LIFX drivers: https://bestow-regional.api.smartthings.com/invite/qyMZoGYJD42m

Beta branch drivers invitation: https://bestow-regional.api.smartthings.com/invite/VD2Nra5KoL25

**Comment by bcandersen** [comment]
Added invitation links to README
